### ISSUE TITLE
Let a config file in `config` part can  read from a local static file

### ISSUE THREAD

**Issue by openinx** [openinx/huker#15]
The `config` part as following:

```yaml
    config:
      zoo.cfg:
        - dataDir={{.PkgDataDir}}
        - dataLogDir={{.PkgLogDir}}
        - clientPort=2182
        - tickTime=2000
        - maxClientCnxns=60
        - initLimit=30
        - syncLimit=20
        - maxSessionTimeout=40000
      {{.PkgDataDir}}/myid:
```

Now we need to put all the properties in  xx.yaml,  for  log config, a better way is to put it into a static file,  and the `config` part can ref to the static file.
