### ISSUE TITLE
Support to start a cluster in a single node

### ISSUE THREAD

**Issue by openinx** [openinx/huker#8]
Now we cann't start a zookeeper cluster in a single node, because current config design can not specific different port for different process with the same job name.

we need to change the `host` part from:

```yaml
hosts:
  - 127.0.0.1
```

to 

```yaml
hosts:
  127.0.0.1/port=9001/id=1:  # host.1
    config:
      zoo.cfg:
        - clientPort=2181
        - server.1=zoo1:2188:3188
  127.0.0.1/port=9001/id=2:  # host.2
    config:
      zoo.cfg:
        - clientPort=2281
        - server.2=zoo1:2288:3288
  127.0.0.1/port=9001/id=3:  # host.3
    config:
      zoo.cfg:
        - clientPort=2381
        - server.3=zoo1:2388:3288
```

BTW, the `base_port` part can be removed now.
